<?php
header("Content-Type: application/download\n");
header("Content-Disposition: attachment; filename=\"Peserta Daftar Ulang PPDB.xls\"");
header("Content-Transfer-Encoding: binary");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: public");
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="Pendaftar%20DU%20PPDB_files/filelist.xml">
<style id="Pendaftar DU PPDB_421_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl63421
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl64421
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl65421
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl66421
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:bottom;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl67421
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Pendaftar DU PPDB_421" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1254 class=xl63421
 style='border-collapse:collapse;table-layout:fixed;width:942pt'>
 <col class=xl63421 width=89 style='mso-width-source:userset;mso-width-alt:
 3254;width:67pt'>
 <col class=xl63421 width=73 style='mso-width-source:userset;mso-width-alt:
 2669;width:55pt'>
 <col class=xl63421 width=189 style='mso-width-source:userset;mso-width-alt:
 6912;width:142pt'>
 <col class=xl63421 width=175 style='mso-width-source:userset;mso-width-alt:
 6400;width:131pt'>
 <col class=xl63421 width=201 style='mso-width-source:userset;mso-width-alt:
 7350;width:151pt'>
 <col class=xl63421 width=109 style='mso-width-source:userset;mso-width-alt:
 3986;width:82pt'>
 <col class=xl63421 width=114 style='mso-width-source:userset;mso-width-alt:
 4169;width:86pt'>
 <col class=xl63421 width=113 style='mso-width-source:userset;mso-width-alt:
 4132;width:85pt'>
 <col class=xl63421 width=127 style='mso-width-source:userset;mso-width-alt:
 4644;width:95pt'>
 <col class=xl63421 width=64 style='width:48pt'>
 <tr height=21 style='height:15.75pt'>
  <td colspan=9 height=21 class=xl67421 width=1190 style='height:15.75pt;
  width:894pt'>Peserta Daftar Ulang Penerimaan Peserta Didik Baru</td>
  <td class=xl63421 width=64 style='width:48pt'></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl63421 style='height:15.0pt'></td>
  <td class=xl63421></td>
  <td class=xl63421></td>
  <td class=xl63421></td>
  <td class=xl63421></td>
  <td class=xl63421></td>
  <td class=xl63421></td>
  <td class=xl63421></td>
  <td class=xl63421></td>
  <td class=xl63421></td>
 </tr>
 <tr height=38 style='height:28.5pt'>
  <td height=38 class=xl64421 width=89 style='height:28.5pt;width:67pt'>Nomor
  Pendaftaran</td>
  <td class=xl64421 width=73 style='border-left:none;width:55pt'>NISN</td>
  <td class=xl64421 width=189 style='border-left:none;width:142pt'>Nama</td>
  <td class=xl64421 width=175 style='border-left:none;width:131pt'>Asal Sekolah</td>
  <td class=xl64421 width=201 style='border-left:none;width:151pt'>Alamat</td>
  <td class=xl64421 width=109 style='border-left:none;width:82pt'>Domisili</td>
  <td class=xl64421 width=114 style='border-left:none;width:86pt'>Jenis Kelamin</td>
  <td class=xl64421 width=113 style='border-left:none;width:85pt'>Tempat Lahir</td>
  <td class=xl64421 width=127 style='border-left:none;width:95pt'>Tanggal Lahir</td>
  <td class=xl65421 width=64 style='width:48pt'></td>
 </tr>
  <?php 
	$i=1;
	  foreach ($tabel_pendaftar_daftarulang_ppdb as $row) {
	?>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl66421 style='height:15.0pt;border-top:none'><?php echo $row->nomor_pendaftaran; ?></td>
  <td class=xl66421 style='border-top:none;border-left:none'><?php echo $row->nisn; ?></td>
  <td class=xl66421 style='border-top:none;border-left:none'><?php echo $row->nama; ?></td>
  <td class=xl66421 style='border-top:none;border-left:none'><?php echo $row->asal_sekolah; ?></td>
  <td class=xl66421 style='border-top:none;border-left:none'><?php echo $row->alamat; ?></td>
  <td class=xl66421 style='border-top:none;border-left:none'><?php echo $row->domisili; ?></td>
  <td class=xl66421 style='border-top:none;border-left:none'><?php echo $row->jenis_kelamin; ?></td>
  <td class=xl66421 style='border-top:none;border-left:none'><?php echo $row->tempat_lahir; ?></td>
  <td class=xl66421 style='border-top:none;border-left:none'><?php echo $row->tanggal_lahir; ?></td>
  <td class=xl63421></td>
 </tr>
 <?php
	$i=$i+1;
	  }
	?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=89 style='width:67pt'></td>
  <td width=73 style='width:55pt'></td>
  <td width=189 style='width:142pt'></td>
  <td width=175 style='width:131pt'></td>
  <td width=201 style='width:151pt'></td>
  <td width=109 style='width:82pt'></td>
  <td width=114 style='width:86pt'></td>
  <td width=113 style='width:85pt'></td>
  <td width=127 style='width:95pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
