<?php
header("Content-Type: application/download\n");
header("Content-Disposition: attachment; filename=\"nilai-$nama_kelas-$nama_mapel-$kategori_nilai-$jenis_na; .xls\"");
header("Content-Transfer-Encoding: binary");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: public");
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 14">
<link rel=File-List href="view_template_nilai_files/filelist.xml">
<style id="view_template_nilai_29138_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl1529138
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6329138
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
.xl6429138
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:11.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Calibri, sans-serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:nowrap;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="view_template_nilai_29138" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=755 style='border-collapse:
 collapse;table-layout:fixed;width:568pt'>
 <col width=34 style='mso-width-source:userset;mso-width-alt:1243;width:26pt'>
 <col width=109 style='mso-width-source:userset;mso-width-alt:3986;width:82pt'>
 <col width=194 style='mso-width-source:userset;mso-width-alt:7094;width:146pt'>
 <col width=98 style='mso-width-source:userset;mso-width-alt:3584;width:74pt'>
 <col width=64 span=5 style='width:48pt'>
 <tr height=24 style='mso-height-source:userset;height:18.0pt'>
  <td colspan=5 rowspan=2 height=43 class=xl6429138 width=499 style='height:
  32.25pt;width:376pt'>Nilai Siswa Kelas <?php echo $nama_kelas; ?></td>
  <td class=xl1529138 width=64 style='width:48pt'></td>
  <td class=xl1529138 width=64 style='width:48pt'></td>
  <td class=xl1529138 width=64 style='width:48pt'></td>
  <td class=xl1529138 width=64 style='width:48pt'></td>
 </tr>
 <tr height=19 style='mso-height-source:userset;height:14.25pt'>
  <td height=19 class=xl1529138 style='height:14.25pt'></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=2 height=20 class=xl6329138 style='height:15.0pt'>Mata
  Pelajaran<span style='mso-spacerun:yes'> </span></td>
  <td class=xl6329138><?php echo $nama_mapel; ?></td>
  <td class=xl6329138><?php echo $id_mapel; ?></td>
  <td class=xl6329138><?php echo $id_kelas_reguler_berjalan; ?></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=2 height=20 class=xl6329138 style='height:15.0pt'>Jenis Penilaian</td>
  <td class=xl6329138><?php echo $jenis_na; ?></td>
  <td class=xl6329138><?php echo $id_jenis_na; ?></td>
  <td class=xl6329138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td colspan=2 height=20 class=xl6329138 style='height:15.0pt'>Kategori Nilai</td>
  <td class=xl6329138><?php echo $kategori_nilai; ?></td>
  <td class=xl6329138><?php echo $id_kategorinilai; ?></td>
  <td class=xl6329138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
 </tr>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1529138 style='height:15.0pt'>No</td>
  <td class=xl1529138>NISN</td>
  <td class=xl1529138>Nama Siswa</td>
  <td class=xl1529138>Nilai Siswa</td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
 </tr>
 <?php
  $i=0;
  foreach($siswaperkelas as $siswa) {
    $i++;
 ?>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1529138 align=right style='height:15.0pt'><?php echo $i; ?></td>
  <td class=xl1529138 align=right><?php echo $siswa->nisn; ?></td>
  <td class=xl1529138><?php echo $siswa->nama; ?></td>
  <td class=xl1529138 align=right><?php echo $nilaisiswa[$siswa->nisn]; ?></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
 </tr>
 <?php
 }
 ?>
 <tr height=20 style='height:15.0pt'>
  <td height=20 class=xl1529138 style='height:15.0pt'></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
  <td class=xl1529138></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=34 style='width:26pt'></td>
  <td width=109 style='width:82pt'></td>
  <td width=194 style='width:146pt'></td>
  <td width=98 style='width:74pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
