<?php
header("Content-Type: application/download\n");
header("Content-Disposition: attachment; filename=\"Pendaftar PPDB Jalur Ujian.xls\"");
header("Content-Transfer-Encoding: binary");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: public");
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="view_excel_ppdb_ujian_files/filelist.xml">
<style id="Pendaftar lolos PPDB (Ujian)_25475_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl6325475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6425475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6525475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6625475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6725475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl6825475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Pendaftar lolos PPDB (Ujian)_25475" align=center
x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=2031 class=xl6325475
 style='border-collapse:collapse;table-layout:fixed;width:1526pt'>
 <col class=xl6325475 width=94 style='mso-width-source:userset;mso-width-alt:
 3437;width:71pt'>
 <col class=xl6325475 width=129 style='mso-width-source:userset;mso-width-alt:
 4717;width:97pt'>
 <col class=xl6325475 width=84 style='mso-width-source:userset;mso-width-alt:
 3072;width:63pt'>
 <col class=xl6325475 width=174 style='mso-width-source:userset;mso-width-alt:
 6363;width:131pt'>
 <col class=xl6325475 width=103 style='mso-width-source:userset;mso-width-alt:
 3766;width:77pt'>
 <col class=xl6325475 width=84 style='mso-width-source:userset;mso-width-alt:
 3072;width:63pt'>
 <col class=xl6325475 width=113 style='mso-width-source:userset;mso-width-alt:
 4132;width:85pt'>
 <col class=xl6325475 width=257 style='mso-width-source:userset;mso-width-alt:
 9398;width:193pt'>
 <col class=xl6325475 width=140 style='mso-width-source:userset;mso-width-alt:
 5120;width:105pt'>
 <col class=xl6325475 width=70 style='mso-width-source:userset;mso-width-alt:
 2560;width:53pt'>
 <col class=xl6325475 width=64 style='width:48pt'>
 <col class=xl6325475 width=78 span=2 style='mso-width-source:userset;
 mso-width-alt:2852;width:59pt'>
 <col class=xl6325475 width=77 style='mso-width-source:userset;mso-width-alt:
 2816;width:58pt'>
 <col class=xl6325475 width=83 style='mso-width-source:userset;mso-width-alt:
 3035;width:62pt'>
 <col class=xl6325475 width=64 span=4 style='width:48pt'>
 <col class=xl6325475 width=83 style='mso-width-source:userset;mso-width-alt:
 3035;width:62pt'>
 <col class=xl6325475 width=64 style='width:48pt'>
 <tr height=26 style='mso-height-source:userset;height:19.5pt'>
  <td colspan=21 height=26 class=xl6425475 width=2031 style='height:19.5pt;
  width:1526pt'>Penerimaan Peserta Didik Baru</td>
 </tr>
 <tr height=22 style='mso-height-source:userset;height:16.5pt'>
  <td colspan=21 height=22 class=xl6425475 width=2031 style='height:16.5pt;
  width:1526pt'>Jalur Ujian<span style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl6325475 width=94 style='height:15.75pt;width:71pt'></td>
  <td class=xl6325475 width=129 style='width:97pt'></td>
  <td class=xl6325475 width=84 style='width:63pt'></td>
  <td class=xl6325475 width=174 style='width:131pt'></td>
  <td class=xl6325475 width=103 style='width:77pt'></td>
  <td class=xl6325475 width=84 style='width:63pt'></td>
  <td class=xl6325475 width=113 style='width:85pt'></td>
  <td class=xl6325475 width=257 style='width:193pt'></td>
  <td class=xl6325475 width=140 style='width:105pt'></td>
  <td class=xl6325475 width=70 style='width:53pt'></td>
  <td class=xl6325475 width=64 style='width:48pt'></td>
  <td class=xl6325475 width=78 style='width:59pt'></td>
  <td class=xl6325475 width=78 style='width:59pt'></td>
  <td class=xl6325475 width=77 style='width:58pt'></td>
  <td class=xl6325475 width=83 style='width:62pt'></td>
  <td class=xl6325475 width=64 style='width:48pt'></td>
  <td class=xl6325475 width=64 style='width:48pt'></td>
  <td class=xl6325475 width=64 style='width:48pt'></td>
  <td class=xl6325475 width=64 style='width:48pt'></td>
  <td class=xl6325475 width=83 style='width:62pt'></td>
  <td class=xl6325475 width=64 style='width:48pt'></td>
 </tr>
 <tr class=xl6425475 height=28 style='mso-height-source:userset;height:21.0pt'>
  <td rowspan=2 height=49 class=xl6525475 width=94 style='height:36.75pt;
  width:71pt'>Nomor Pendaftar</td>
  <td rowspan=2 class=xl6525475 width=129 style='width:97pt'>Nomor USBN</td>
  <td rowspan=2 class=xl6525475 width=84 style='width:63pt'>NISN</td>
  <td rowspan=2 class=xl6525475 width=174 style='width:131pt'>Nama</td>
  <td rowspan=2 class=xl6525475 width=103 style='width:77pt'>Jenis Kelamin</td>
  <td rowspan=2 class=xl6525475 width=84 style='width:63pt'>Tempat Lahir</td>
  <td rowspan=2 class=xl6525475 width=113 style='width:85pt'>Tanggal Lahir</td>
  <td rowspan=2 class=xl6525475 width=257 style='width:193pt'>Alamat</td>
  <td rowspan=2 class=xl6525475 width=140 style='width:105pt'>Asal Sekolah</td>
  <td rowspan=2 class=xl6525475 width=70 style='width:53pt'>Tahun Lulus</td>
  <td colspan=11 class=xl6525475 width=783 style='border-left:none;width:588pt'>Nilai<span
  style='mso-spacerun:yes'> </span></td>
 </tr>
 <tr class=xl6425475 height=21 style='height:15.75pt'>
  <td height=21 class=xl6525475 width=64 style='height:15.75pt;border-top:none;
  border-left:none;width:48pt'>Ujian 1</td>
  <td class=xl6525475 width=78 style='border-top:none;border-left:none;
  width:59pt'>Ujian 2</td>
  <td class=xl6525475 width=78 style='border-top:none;border-left:none;
  width:59pt'>Ujian 3</td>
  <td class=xl6525475 width=77 style='border-top:none;border-left:none;
  width:58pt'>Ujian 4</td>
  <td class=xl6525475 width=83 style='border-top:none;border-left:none;
  width:62pt'>Ujian 5</td>
  <td class=xl6525475 width=64 style='border-top:none;border-left:none;
  width:48pt'>Ujian 6</td>
  <td class=xl6525475 width=64 style='border-top:none;border-left:none;
  width:48pt'>Ujian 7</td>
  <td class=xl6525475 width=64 style='border-top:none;border-left:none;
  width:48pt'>Ujian 8</td>
  <td class=xl6525475 width=64 style='border-top:none;border-left:none;
  width:48pt'>Ujian 9</td>
  <td class=xl6525475 width=83 style='border-top:none;border-left:none;
  width:62pt'>Ujian 10</td>
  <td class=xl6525475 width=64 style='border-top:none;border-left:none;
  width:48pt'>Total</td>
 </tr>
<?php 
  $i=1;
  foreach ($tabel_pendaftar_ppdb_lolos as $row) 
  {
    ?>
 <tr class=xl6825475 height=43 style='mso-height-source:userset;height:32.25pt'>
  <td height=43 class=xl6625475 width=94 style='height:32.25pt;border-top:none;
  width:71pt'><?php echo $row->nomor_pendaftaran; ?></td>
  <td class=xl6725475 width=129 style='border-top:none;border-left:none;
  width:97pt'><?php echo $row->no_usbn; ?></td>
  <td class=xl6725475 width=84 style='border-top:none;border-left:none;
  width:63pt'><?php echo $row->nisn_pendaftar; ?></td>
  <td class=xl6725475 width=174 style='border-top:none;border-left:none;
  width:131pt'><?php echo $row->nama; ?></td>
  <td class=xl6725475 width=103 style='border-top:none;border-left:none;
  width:77pt'><?php echo $row->jenis_kelamin; ?></td>
  <td class=xl6725475 width=84 style='border-top:none;border-left:none;
  width:63pt'><?php echo $row->tempat_lahir; ?></td>
  <td class=xl6725475 width=113 style='border-top:none;border-left:none;
  width:85pt'><?php echo $row->tanggal_lahir; ?></td>
  <td class=xl6725475 width=257 style='border-top:none;border-left:none;
  width:193pt'><?php echo $row->alamat; ?></td>
  <td class=xl6725475 width=140 style='border-top:none;border-left:none;
  width:105pt'><?php echo $row->asal_sekolah; ?></td>
  <td class=xl6725475 width=70 style='border-top:none;border-left:none;
  width:53pt'><?php echo $row->tahun_lulus; ?></td>
  <td class=xl6725475 width=64 style='border-top:none;border-left:none;
  width:48pt'><?php echo $row->ujian_1; ?></td>
  <td class=xl6725475 width=78 style='border-top:none;border-left:none;
  width:59pt'><?php echo $row->ujian_2; ?></td>
  <td class=xl6725475 width=78 style='border-top:none;border-left:none;
  width:59pt'><?php echo $row->ujian_3; ?></td>
  <td class=xl6725475 width=77 style='border-top:none;border-left:none;
  width:58pt'><?php echo $row->ujian_4; ?></td>
  <td class=xl6725475 width=83 style='border-top:none;border-left:none;
  width:62pt'><?php echo $row->ujian_5; ?></td>
  <td class=xl6725475 width=64 style='border-top:none;border-left:none;
  width:48pt'><?php echo $row->ujian_6; ?></td>
  <td class=xl6725475 width=64 style='border-top:none;border-left:none;
  width:48pt'><?php echo $row->ujian_7; ?></td>
  <td class=xl6725475 width=64 style='border-top:none;border-left:none;
  width:48pt'><?php echo $row->ujian_8; ?></td>
  <td class=xl6725475 width=64 style='border-top:none;border-left:none;
  width:48pt'><?php echo $row->ujian_9; ?></td>
  <td class=xl6725475 width=83 style='border-top:none;border-left:none;
  width:62pt'><?php echo $row->ujian_10; ?></td>
  <td class=xl6725475 width=64 style='border-top:none;border-left:none;
  width:48pt'><?php echo $row->total_nilai; ?></td>
 </tr>
 <?php
    $i=$i+1;
  }
  ?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=94 style='width:71pt'></td>
  <td width=129 style='width:97pt'></td>
  <td width=84 style='width:63pt'></td>
  <td width=174 style='width:131pt'></td>
  <td width=103 style='width:77pt'></td>
  <td width=84 style='width:63pt'></td>
  <td width=113 style='width:85pt'></td>
  <td width=257 style='width:193pt'></td>
  <td width=140 style='width:105pt'></td>
  <td width=70 style='width:53pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=78 style='width:59pt'></td>
  <td width=78 style='width:59pt'></td>
  <td width=77 style='width:58pt'></td>
  <td width=83 style='width:62pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=83 style='width:62pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
