<?php
header("Content-Type: application/download\n");
header("Content-Disposition: attachment; filename=\"Pendaftar PPDB Jalur Nilai Ujian Nasional.xls\"");
header("Content-Transfer-Encoding: binary");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Pragma: public");
?>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link rel=File-List href="Pendaftar%20lolos%20PPDB%20(UN)_files/filelist.xml">
<style id="Pendaftar lolos PPDB (UN)_1475_Styles">
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
.xl631475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl641475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl651475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:general;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl661475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	border:.5pt solid windowtext;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl671475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:12.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:middle;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
.xl681475
	{padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:black;
	font-size:14.0pt;
	font-weight:700;
	font-style:normal;
	text-decoration:none;
	font-family:"Times New Roman", serif;
	mso-font-charset:0;
	mso-number-format:"\@";
	text-align:center;
	vertical-align:bottom;
	mso-background-source:auto;
	mso-pattern:auto;
	white-space:normal;}
-->
</style>
</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Pendaftar lolos PPDB (UN)_1475" align=center x:publishsource="Excel">

<table border=0 cellpadding=0 cellspacing=0 width=1709 class=xl631475
 style='border-collapse:collapse;table-layout:fixed;width:1284pt'>
 <col class=xl631475 width=98 style='mso-width-source:userset;mso-width-alt:
 3584;width:74pt'>
 <col class=xl631475 width=121 style='mso-width-source:userset;mso-width-alt:
 4425;width:91pt'>
 <col class=xl631475 width=84 style='mso-width-source:userset;mso-width-alt:
 3072;width:63pt'>
 <col class=xl631475 width=174 style='mso-width-source:userset;mso-width-alt:
 6363;width:131pt'>
 <col class=xl631475 width=103 style='mso-width-source:userset;mso-width-alt:
 3766;width:77pt'>
 <col class=xl631475 width=84 style='mso-width-source:userset;mso-width-alt:
 3072;width:63pt'>
 <col class=xl631475 width=113 style='mso-width-source:userset;mso-width-alt:
 4132;width:85pt'>
 <col class=xl631475 width=257 style='mso-width-source:userset;mso-width-alt:
 9398;width:193pt'>
 <col class=xl631475 width=140 style='mso-width-source:userset;mso-width-alt:
 5120;width:105pt'>
 <col class=xl631475 width=91 style='mso-width-source:userset;mso-width-alt:
 3328;width:68pt'>
 <col class=xl631475 width=64 style='width:48pt'>
 <col class=xl631475 width=78 span=2 style='mso-width-source:userset;
 mso-width-alt:2852;width:59pt'>
 <col class=xl631475 width=77 style='mso-width-source:userset;mso-width-alt:
 2816;width:58pt'>
 <col class=xl631475 width=83 style='mso-width-source:userset;mso-width-alt:
 3035;width:62pt'>
 <col class=xl631475 width=64 style='width:48pt'>
 <tr height=27 style='mso-height-source:userset;height:20.25pt'>
  <td colspan=16 height=27 class=xl681475 width=1709 style='height:20.25pt;
  width:1284pt'>Penerimaan Peserta Didik Baru</td>
 </tr>
 <tr height=28 style='mso-height-source:userset;height:21.0pt'>
  <td colspan=16 height=28 class=xl681475 width=1709 style='height:21.0pt;
  width:1284pt'>Jalur Ujian Nasional</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl631475 width=98 style='height:15.75pt;width:74pt'></td>
  <td class=xl631475 width=121 style='width:91pt'></td>
  <td class=xl631475 width=84 style='width:63pt'></td>
  <td class=xl631475 width=174 style='width:131pt'></td>
  <td class=xl631475 width=103 style='width:77pt'></td>
  <td class=xl631475 width=84 style='width:63pt'></td>
  <td class=xl631475 width=113 style='width:85pt'></td>
  <td class=xl631475 width=257 style='width:193pt'></td>
  <td class=xl631475 width=140 style='width:105pt'></td>
  <td class=xl631475 width=91 style='width:68pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
  <td class=xl631475 width=78 style='width:59pt'></td>
  <td class=xl631475 width=78 style='width:59pt'></td>
  <td class=xl631475 width=77 style='width:58pt'></td>
  <td class=xl631475 width=83 style='width:62pt'></td>
  <td class=xl631475 width=64 style='width:48pt'></td>
 </tr>
 <tr class=xl671475 height=42 style='height:31.5pt'>
  <td height=42 class=xl661475 width=98 style='height:31.5pt;width:74pt'>Nomor
  Pendaftar</td>
  <td class=xl661475 width=121 style='border-left:none;width:91pt'>Nomor USBN</td>
  <td class=xl661475 width=84 style='border-left:none;width:63pt'>NISN</td>
  <td class=xl661475 width=174 style='border-left:none;width:131pt'>Nama</td>
  <td class=xl661475 width=103 style='border-left:none;width:77pt'>Jenis
  Kelamin</td>
  <td class=xl661475 width=84 style='border-left:none;width:63pt'>Tempat Lahir</td>
  <td class=xl661475 width=113 style='border-left:none;width:85pt'>Tanggal
  Lahir</td>
  <td class=xl661475 width=257 style='border-left:none;width:193pt'>Alamat</td>
  <td class=xl661475 width=140 style='border-left:none;width:105pt'>Asal
  Sekolah</td>
  <td class=xl661475 width=91 style='border-left:none;width:68pt'>Domisili</td>
  <td class=xl661475 width=64 style='border-left:none;width:48pt'>Tahun Lulus</td>
  <td class=xl661475 width=78 style='border-left:none;width:59pt'>Nilai UN B.
  Ind</td>
  <td class=xl661475 width=78 style='border-left:none;width:59pt'>Nilai UN Mat</td>
  <td class=xl661475 width=77 style='border-left:none;width:58pt'>Nilai UN IPA</td>
  <td class=xl661475 width=83 style='border-left:none;width:62pt'><span
  style='mso-spacerun:yes'> </span>Nilai Prestasi<span
  style='mso-spacerun:yes'> </span></td>
  <td class=xl661475 width=64 style='border-left:none;width:48pt'>Nilai total</td>
 </tr>
 <?php 
$i=1;
foreach ($tabel_pendaftar_ppdb_lolos as $row) 
{
  ?>
 <tr class=xl651475 height=46 style='mso-height-source:userset;height:34.5pt'>
  <td height=46 class=xl641475 width=98 style='height:34.5pt;border-top:none;
  width:74pt'><?php echo $row->nomor_pendaftaran; ?></td>
  <td class=xl641475 width=121 style='border-top:none;border-left:none;
  width:91pt'><?php echo $row->no_usbn; ?></td>
  <td class=xl641475 width=84 style='border-top:none;border-left:none;
  width:63pt'><?php echo $row->nisn_pendaftar; ?></td>
  <td class=xl641475 width=174 style='border-top:none;border-left:none;
  width:131pt'><?php echo $row->nama; ?></td>
  <td class=xl641475 width=103 style='border-top:none;border-left:none;
  width:77pt'><?php echo $row->jenis_kelamin; ?></td>
  <td class=xl641475 width=84 style='border-top:none;border-left:none;
  width:63pt'><?php echo $row->tempat_lahir; ?></td>
  <td class=xl641475 width=113 style='border-top:none;border-left:none;
  width:85pt'><?php echo $row->tanggal_lahir; ?></td>
  <td class=xl641475 width=257 style='border-top:none;border-left:none;
  width:193pt'><?php echo $row->alamat; ?></td>
  <td class=xl641475 width=140 style='border-top:none;border-left:none;
  width:105pt'><?php echo $row->asal_sekolah; ?></td>
  <td class=xl641475 width=91 style='border-top:none;border-left:none;
  width:68pt'><?php echo $row->domisili; ?></td>
  <td class=xl641475 width=64 style='border-top:none;border-left:none;
  width:48pt'><?php echo $row->tahun_lulus; ?></td>
  <td class=xl641475 width=78 style='border-top:none;border-left:none;
  width:59pt'><?php echo $row->nilai_un_ind; ?></td>
  <td class=xl641475 width=78 style='border-top:none;border-left:none;
  width:59pt'><?php echo $row->nilai_un_mat; ?></td>
  <td class=xl641475 width=77 style='border-top:none;border-left:none;
  width:58pt'><?php echo $row->nilai_un_ipa; ?></td>
  <td class=xl641475 width=83 style='border-top:none;border-left:none;
  width:62pt'><?php echo $row->nilai_prestasi; ?></td>
  <td class=xl641475 width=64 style='border-top:none;border-left:none;
  width:48pt'><?php echo $row->nilai_un_nun; ?></td>
 </tr>
 <?php
  $i=$i+1;
}
?>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=98 style='width:74pt'></td>
  <td width=121 style='width:91pt'></td>
  <td width=84 style='width:63pt'></td>
  <td width=174 style='width:131pt'></td>
  <td width=103 style='width:77pt'></td>
  <td width=84 style='width:63pt'></td>
  <td width=113 style='width:85pt'></td>
  <td width=257 style='width:193pt'></td>
  <td width=140 style='width:105pt'></td>
  <td width=91 style='width:68pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=78 style='width:59pt'></td>
  <td width=78 style='width:59pt'></td>
  <td width=77 style='width:58pt'></td>
  <td width=83 style='width:62pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
